version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: "echo and env var that is part of our project"
          command: |
            echo $My_Env_Var


workflows:
  test_env_var:
    jobs:
      - build
